name: Release

on:
  push:
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-latest

    if: github.event.base_ref == 'refs/heads/main'

    steps:
      - uses: "actions/checkout@v4"

      - name: "Build pack"
        run: |
          cd src
          zip ../${{ github.event.repository.name }}-${{ github.ref_name }}.zip *

      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          files: ${{ github.event.repository.name }}-${{ github.ref_name }}.zip