name: "release"

on:
  push:
    tags:
      - v*

jobs:
  release:
    name: "Checkout build release"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"

      - name: "Build pack"
        run: |
          cd src
          zip ../${{ github.event.repository.name }}-${{ github.ref_name }}-${{ github.event.head_commit.message }}.zip *

      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          files: ${{ github.event.repository.name }}-${{ github.ref_name }}-${{ github.event.head_commit.message }}.zip
          title: Rainbow XP Bar ${{ github.ref_name }} - ${{ github.event.head_commit.message }}
